name: Code Check
on: [push]
jobs:
  code-check:
    name: Code Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Restore project deps
        run: npm ci

      - name: Code format check
        run: npm run ci:prettier

      - name: Typescript typecheck
        run: npm run ci:typecheck

      - name: ESLint check (skip env var validation)
        run: npm run ci:lint
